trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Terraform-Credentials

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: PlanJob
    displayName: 'Run Terraform Plan'
    
    steps:

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendAzureRmUseEnvironmentVariablesForAuthentication: false
        backendAzureRmUseEntraIdForAuthentication: false
        backendServiceArm: 'Ahamed-Subscription(9211ca43-4409-4921-b493-413dc5e72c82)'
        backendAzureRmResourceGroupName: 'DefaultResourceGroup-EUS'
        backendAzureRmStorageAccountName: 'demostorage3000'
        backendAzureRmContainerName: 'tf-blob'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'validate'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-out="terraform-plan.tfplan"'
        environmentServiceNameAzureRM: 'Ahamed-Subscription(9211ca43-4409-4921-b493-413dc5e72c82)'
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'terraform-plan'
        publishLocation: 'pipeline'
        
    